name: Backend Cloud Run Deployment

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build
        env:
          IMAGE_NAME: backend
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |-
          gcloud artifacts repositories list --location=us-central1
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/${{ vars.GCR_REPO_NAME }}/$IMAGE_NAME:latest -f backend/Dockerfile backend/.
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/${{ vars.GCR_REPO_NAME }}/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chat-app \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCR_REPO_NAME }}/backend:latest \
            --platform managed \
            --region us-central1 \
            --set-env-vars ALLOWED_URL=${{vars.ALLOWED_URL}} \
            --allow-unauthenticated
